# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - xy-learn

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8655d121ea454fd68f6019d5dc21f641 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_41bf72d727084b60bbba244b9b8e7a7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_8655d121ea454fd68f6019d5dc21f641 }}/deploy-container-on-azure/mycontainer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'xy-learn'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39bf6348b7114f4cb1cf3695794b4355 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_8655d121ea454fd68f6019d5dc21f641 }}/deploy-container-on-azure/mycontainer:${{ github.sha }}'